declare let YEXT_PUBLIC_UNIVERSE: string;
declare let YEXT_PUBLIC_EXTERNAL_IMAGE_API_BASE_URL: string;
declare let YEXT_PUBLIC_GOOGLE_MAPS_API_KEY: string;
declare let YEXT_PUBLIC_REVIEWS_API_KEY: string;
declare let YEXT_PUBLIC_SEARCH_APIKEY: string;
declare let YEXT_PUBLIC_SEARCH_EXPKEY: string;
declare let YEXT_PUBLIC_CHAT_APIKEY: string;
declare let YEXT_PUBLIC_CHAT_BOTKEY: string;
declare let YEXT_PUBLIC_ANALYTICS_API_KEY: string;